stages:
  - build
  - deploy

before_script:
  # Install nvm if not already installed
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  # Source nvm
  - export NVM_DIR="$HOME/.nvm"
  - source ~/.bashrc
  - nvm install 18.17.1
  - nvm use 18.17.1
  - npm i -f
  - npm i -g pm2

build:
  stage: build
  script:
    - npx expo export -p web

deploy:
  stage: deploy
  script:
    # Attempt to delete the 'stage' process, and ignore error if it doesn't exist
    - pm2 delete stage || true
    # Start a new process with name 'stage'
    - pm2 start npx --name stage -- serve -l 3005 -s dist
  only:
    - stage
