stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18.17.1"

before_script:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION
  - npm install

build:
  stage: build
  script:
    - npx expo export -p web

deploy:
  stage: deploy
  script:
    - pm2 start npx --name stage -- serve -l 3005 -s dist
  only:
    - stage
