export type CountryType = {
  callingCode: string
  flag: string
  countryCode: string
  name: string
}
export const data: CountryType[] = [
  { callingCode: "+1", flag: "🇨🇦", countryCode: "CA", name: "Canada" },
  { callingCode: "+1", flag: "🇺🇸", countryCode: "US", name: "United States" },
  { callingCode: "+1242", flag: "🇧🇸", countryCode: "BS", name: "Bahamas" },
  { callingCode: "+1246", flag: "🇧🇧", countryCode: "BB", name: "Barbados" },
  { callingCode: "+1264", flag: "🇦🇮", countryCode: "AI", name: "Anguilla" },
  { callingCode: "+1268", flag: "🇦🇬", countryCode: "AG", name: "Antigua and Barbuda" },
  { callingCode: "+1284", flag: "🇻🇬", countryCode: "VG", name: "Virgin Islands, British" },
  { callingCode: "+1340", flag: "🇻🇮", countryCode: "VI", name: "Virgin Islands, U.S." },
  { callingCode: "+1441", flag: "🇧🇲", countryCode: "BM", name: "Bermuda" },
  { callingCode: "+1473", flag: "🇬🇩", countryCode: "GD", name: "Grenada" },
  { callingCode: "+1649", flag: "🇹🇨", countryCode: "TC", name: "Turks and Caicos Islands" },
  { callingCode: "+1664", flag: "🇲🇸", countryCode: "MS", name: "Montserrat" },
  { callingCode: "+1670", flag: "🇲🇵", countryCode: "MP", name: "Northern Mariana Islands" },
  { callingCode: "+1671", flag: "🇬🇺", countryCode: "GU", name: "Guam" },
  { callingCode: "+1684", flag: "🇦🇸", countryCode: "AS", name: "American Samoa" },
  { callingCode: "+1758", flag: "🇱🇨", countryCode: "LC", name: "Saint Lucia" },
  { callingCode: "+1767", flag: "🇩🇲", countryCode: "DM", name: "Dominica" },
  { callingCode: "+1784", flag: "🇻🇨", countryCode: "VC", name: "Saint Vincent and the Grenadines" },
  { callingCode: "+1849", flag: "🇩🇴", countryCode: "DO", name: "Dominican Republic" },
  { callingCode: "+1868", flag: "🇹🇹", countryCode: "TT", name: "Trinidad and Tobago" },
  { callingCode: "+1869", flag: "🇰🇳", countryCode: "KN", name: "Saint Kitts and Nevis" },
  { callingCode: "+1876", flag: "🇯🇲", countryCode: "JM", name: "Jamaica" },
  { callingCode: "+1939", flag: "🇵🇷", countryCode: "PR", name: "Puerto Rico" },
  { callingCode: "+20", flag: "🇪🇬", countryCode: "EG", name: "Egypt" },
  { callingCode: "+211", flag: "🇸🇸", countryCode: "SS", name: "South Sudan" },
  { callingCode: "+212", flag: "🇲🇦", countryCode: "MA", name: "Morocco" },
  { callingCode: "+213", flag: "🇩🇿", countryCode: "DZ", name: "Algeria" },
  { callingCode: "+216", flag: "🇹🇳", countryCode: "TN", name: "Tunisia" },
  { callingCode: "+218", flag: "🇱🇾", countryCode: "LY", name: "Libyan Arab Jamahiriya" },
  { callingCode: "+220", flag: "🇬🇲", countryCode: "GM", name: "Gambia" },
  { callingCode: "+221", flag: "🇸🇳", countryCode: "SN", name: "Senegal" },
  { callingCode: "+222", flag: "🇲🇷", countryCode: "MR", name: "Mauritania" },
  { callingCode: "+223", flag: "🇲🇱", countryCode: "ML", name: "Mali" },
  { callingCode: "+224", flag: "🇬🇳", countryCode: "GN", name: "Guinea" },
  { callingCode: "+225", flag: "🇨🇮", countryCode: "CI", name: "Cote d'Ivoire" },
  { callingCode: "+226", flag: "🇧🇫", countryCode: "BF", name: "Burkina Faso" },
  { callingCode: "+227", flag: "🇳🇪", countryCode: "NE", name: "Niger" },
  { callingCode: "+228", flag: "🇹🇬", countryCode: "TG", name: "Togo" },
  { callingCode: "+229", flag: "🇧🇯", countryCode: "BJ", name: "Benin" },
  { callingCode: "+230", flag: "🇲🇺", countryCode: "MU", name: "Mauritius" },
  { callingCode: "+231", flag: "🇱🇷", countryCode: "LR", name: "Liberia" },
  { callingCode: "+232", flag: "🇸🇱", countryCode: "SL", name: "Sierra Leone" },
  { callingCode: "+233", flag: "🇬🇭", countryCode: "GH", name: "Ghana" },
  { callingCode: "+234", flag: "🇳🇬", countryCode: "NG", name: "Nigeria" },
  { callingCode: "+235", flag: "🇹🇩", countryCode: "TD", name: "Chad" },
  { callingCode: "+236", flag: "🇨🇫", countryCode: "CF", name: "Central African Republic" },
  { callingCode: "+237", flag: "🇨🇲", countryCode: "CM", name: "Cameroon" },
  { callingCode: "+238", flag: "🇨🇻", countryCode: "CV", name: "Cape Verde" },
  { callingCode: "+239", flag: "🇸🇹", countryCode: "ST", name: "Sao Tome and Principe" },
  { callingCode: "+240", flag: "🇬🇶", countryCode: "GQ", name: "Equatorial Guinea" },
  { callingCode: "+241", flag: "🇬🇦", countryCode: "GA", name: "Gabon" },
  { callingCode: "+242", flag: "🇨🇬", countryCode: "CG", name: "Congo" },
  { callingCode: "+243", flag: "🇨🇩", countryCode: "CD", name: "Congo, The Democratic Republic of the Congo" },
  { callingCode: "+244", flag: "🇦🇴", countryCode: "AO", name: "Angola" },
  { callingCode: "+245", flag: "🇬🇼", countryCode: "GW", name: "Guinea-Bissau" },
  { callingCode: "+246", flag: "🇮🇴", countryCode: "IO", name: "British Indian Ocean Territory" },
  { callingCode: "+248", flag: "🇸🇨", countryCode: "SC", name: "Seychelles" },
  { callingCode: "+249", flag: "🇸🇩", countryCode: "SD", name: "Sudan" },
  { callingCode: "+250", flag: "🇷🇼", countryCode: "RW", name: "Rwanda" },
  { callingCode: "+251", flag: "🇪🇹", countryCode: "ET", name: "Ethiopia" },
  { callingCode: "+252", flag: "🇸🇴", countryCode: "SO", name: "Somalia" },
  { callingCode: "+253", flag: "🇩🇯", countryCode: "DJ", name: "Djibouti" },
  { callingCode: "+254", flag: "🇰🇪", countryCode: "KE", name: "Kenya" },
  { callingCode: "+255", flag: "🇹🇿", countryCode: "TZ", name: "Tanzania, United Republic of Tanzania" },
  { callingCode: "+256", flag: "🇺🇬", countryCode: "UG", name: "Uganda" },
  { callingCode: "+257", flag: "🇧🇮", countryCode: "BI", name: "Burundi" },
  { callingCode: "+258", flag: "🇲🇿", countryCode: "MZ", name: "Mozambique" },
  { callingCode: "+260", flag: "🇿🇲", countryCode: "ZM", name: "Zambia" },
  { callingCode: "+261", flag: "🇲🇬", countryCode: "MG", name: "Madagascar" },
  { callingCode: "+262", flag: "🇹🇫", countryCode: "TF", name: "French Southern Territories" },
  { callingCode: "+262", flag: "🇾🇹", countryCode: "YT", name: "Mayotte" },
  { callingCode: "+262", flag: "🇷🇪", countryCode: "RE", name: "Reunion" },
  { callingCode: "+263", flag: "🇿🇼", countryCode: "ZW", name: "Zimbabwe" },
  { callingCode: "+264", flag: "🇳🇦", countryCode: "NA", name: "Namibia" },
  { callingCode: "+265", flag: "🇲🇼", countryCode: "MW", name: "Malawi" },
  { callingCode: "+266", flag: "🇱🇸", countryCode: "LS", name: "Lesotho" },
  { callingCode: "+267", flag: "🇧🇼", countryCode: "BW", name: "Botswana" },
  { callingCode: "+268", flag: "🇸🇿", countryCode: "SZ", name: "Swaziland" },
  { callingCode: "+269", flag: "🇰🇲", countryCode: "KM", name: "Comoros" },
  { callingCode: "+27", flag: "🇿🇦", countryCode: "ZA", name: "South Africa" },
  { callingCode: "+290", flag: "🇸🇭", countryCode: "SH", name: "Saint Helena, Ascension and Tristan Da Cunha" },
  { callingCode: "+291", flag: "🇪🇷", countryCode: "ER", name: "Eritrea" },
  { callingCode: "+297", flag: "🇦🇼", countryCode: "AW", name: "Aruba" },
  { callingCode: "+298", flag: "🇫🇴", countryCode: "FO", name: "Faroe Islands" },
  { callingCode: "+299", flag: "🇬🇱", countryCode: "GL", name: "Greenland" },
  { callingCode: "+30", flag: "🇬🇷", countryCode: "GR", name: "Greece" },
  { callingCode: "+31", flag: "🇳🇱", countryCode: "NL", name: "Netherlands" },
  { callingCode: "+32", flag: "🇧🇪", countryCode: "BE", name: "Belgium" },
  { callingCode: "+33", flag: "🇫🇷", countryCode: "FR", name: "France" },
  { callingCode: "+34", flag: "🇪🇸", countryCode: "ES", name: "Spain" },
  { callingCode: "+345", flag: "🇰🇾", countryCode: "KY", name: "Cayman Islands" },
  { callingCode: "+350", flag: "🇬🇮", countryCode: "GI", name: "Gibraltar" },
  { callingCode: "+351", flag: "🇵🇹", countryCode: "PT", name: "Portugal" },
  { callingCode: "+352", flag: "🇱🇺", countryCode: "LU", name: "Luxembourg" },
  { callingCode: "+353", flag: "🇮🇪", countryCode: "IE", name: "Ireland" },
  { callingCode: "+354", flag: "🇮🇸", countryCode: "IS", name: "Iceland" },
  { callingCode: "+355", flag: "🇦🇱", countryCode: "AL", name: "Albania" },
  { callingCode: "+356", flag: "🇲🇹", countryCode: "MT", name: "Malta" },
  { callingCode: "+357", flag: "🇨🇾", countryCode: "CY", name: "Cyprus" },
  { callingCode: "+358", flag: "🇦🇽", countryCode: "AX", name: "Åland Islands" },
  { callingCode: "+358", flag: "🇫🇮", countryCode: "FI", name: "Finland" },
  { callingCode: "+359", flag: "🇧🇬", countryCode: "BG", name: "Bulgaria" },
  { callingCode: "+36", flag: "🇭🇺", countryCode: "HU", name: "Hungary" },
  { callingCode: "+370", flag: "🇱🇹", countryCode: "LT", name: "Lithuania" },
  { callingCode: "+371", flag: "🇱🇻", countryCode: "LV", name: "Latvia" },
  { callingCode: "+372", flag: "🇪🇪", countryCode: "EE", name: "Estonia" },
  { callingCode: "+373", flag: "🇲🇩", countryCode: "MD", name: "Moldova" },
  { callingCode: "+374", flag: "🇦🇲", countryCode: "AM", name: "Armenia" },
  { callingCode: "+375", flag: "🇧🇾", countryCode: "BY", name: "Belarus" },
  { callingCode: "+376", flag: "🇦🇩", countryCode: "AD", name: "Andorra" },
  { callingCode: "+377", flag: "🇲🇨", countryCode: "MC", name: "Monaco" },
  { callingCode: "+378", flag: "🇸🇲", countryCode: "SM", name: "San Marino" },
  { callingCode: "+379", flag: "🇻🇦", countryCode: "VA", name: "Holy See (Vatican City State)" },
  { callingCode: "+380", flag: "🇺🇦", countryCode: "UA", name: "Ukraine" },
  { callingCode: "+381", flag: "🇷🇸", countryCode: "RS", name: "Serbia" },
  { callingCode: "+382", flag: "🇲🇪", countryCode: "ME", name: "Montenegro" },
  { callingCode: "+383", flag: "🇽🇰", countryCode: "XK", name: "Kosovo" },
  { callingCode: "+385", flag: "🇭🇷", countryCode: "HR", name: "Croatia" },
  { callingCode: "+386", flag: "🇸🇮", countryCode: "SI", name: "Slovenia" },
  { callingCode: "+387", flag: "🇧🇦", countryCode: "BA", name: "Bosnia and Herzegovina" },
  { callingCode: "+389", flag: "🇲🇰", countryCode: "MK", name: "North Macedonia" },
  { callingCode: "+39", flag: "🇮🇹", countryCode: "IT", name: "Italy" },
  { callingCode: "+40", flag: "🇷🇴", countryCode: "RO", name: "Romania" },
  { callingCode: "+41", flag: "🇨🇭", countryCode: "CH", name: "Switzerland" },
  { callingCode: "+420", flag: "🇨🇿", countryCode: "CZ", name: "Czech Republic" },
  { callingCode: "+421", flag: "🇸🇰", countryCode: "SK", name: "Slovakia" },
  { callingCode: "+423", flag: "🇱🇮", countryCode: "LI", name: "Liechtenstein" },
  { callingCode: "+43", flag: "🇦🇹", countryCode: "AT", name: "Austria" },
  { callingCode: "+44", flag: "🇬🇬", countryCode: "GG", name: "Guernsey" },
  { callingCode: "+44", flag: "🇮🇲", countryCode: "IM", name: "Isle of Man" },
  { callingCode: "+44", flag: "🇯🇪", countryCode: "JE", name: "Jersey" },
  { callingCode: "+44", flag: "🇬🇧", countryCode: "GB", name: "United Kingdom" },
  { callingCode: "+45", flag: "🇩🇰", countryCode: "DK", name: "Denmark" },
  { callingCode: "+46", flag: "🇸🇪", countryCode: "SE", name: "Sweden" },
  { callingCode: "+47", flag: "🇧🇻", countryCode: "BV", name: "Bouvet Island" },
  { callingCode: "+47", flag: "🇳🇴", countryCode: "NO", name: "Norway" },
  { callingCode: "+47", flag: "🇸🇯", countryCode: "SJ", name: "Svalbard and Jan Mayen" },
  { callingCode: "+48", flag: "🇵🇱", countryCode: "PL", name: "Poland" },
  { callingCode: "+49", flag: "🇩🇪", countryCode: "DE", name: "Germany" },
  { callingCode: "+500", flag: "🇫🇰", countryCode: "FK", name: "Falkland Islands (Malvinas)" },
  { callingCode: "+500", flag: "🇬🇸", countryCode: "GS", name: "South Georgia and the South Sandwich Islands" },
  { callingCode: "+501", flag: "🇧🇿", countryCode: "BZ", name: "Belize" },
  { callingCode: "+502", flag: "🇬🇹", countryCode: "GT", name: "Guatemala" },
  { callingCode: "+503", flag: "🇸🇻", countryCode: "SV", name: "El Salvador" },
  { callingCode: "+504", flag: "🇭🇳", countryCode: "HN", name: "Honduras" },
  { callingCode: "+505", flag: "🇳🇮", countryCode: "NI", name: "Nicaragua" },
  { callingCode: "+506", flag: "🇨🇷", countryCode: "CR", name: "Costa Rica" },
  { callingCode: "+507", flag: "🇵🇦", countryCode: "PA", name: "Panama" },
  { callingCode: "+508", flag: "🇵🇲", countryCode: "PM", name: "Saint Pierre and Miquelon" },
  { callingCode: "+509", flag: "🇭🇹", countryCode: "HT", name: "Haiti" },
  { callingCode: "+51", flag: "🇵🇪", countryCode: "PE", name: "Peru" },
  { callingCode: "+52", flag: "🇲🇽", countryCode: "MX", name: "Mexico" },
  { callingCode: "+53", flag: "🇨🇺", countryCode: "CU", name: "Cuba" },
  { callingCode: "+54", flag: "🇦🇷", countryCode: "AR", name: "Argentina" },
  { callingCode: "+55", flag: "🇧🇷", countryCode: "BR", name: "Brazil" },
  { callingCode: "+56", flag: "🇨🇱", countryCode: "CL", name: "Chile" },
  { callingCode: "+57", flag: "🇨🇴", countryCode: "CO", name: "Colombia" },
  { callingCode: "+58", flag: "🇻🇪", countryCode: "VE", name: "Venezuela, Bolivarian Republic of Venezuela" },
  { callingCode: "+590", flag: "🇬🇵", countryCode: "GP", name: "Guadeloupe" },
  { callingCode: "+590", flag: "🇧🇱", countryCode: "BL", name: "Saint Barthelemy" },
  { callingCode: "+590", flag: "🇲🇫", countryCode: "MF", name: "Saint Martin" },
  { callingCode: "+591", flag: "🇧🇴", countryCode: "BO", name: "Bolivia, Plurinational State of bolivia" },
  { callingCode: "+592", flag: "🇬🇾", countryCode: "GY", name: "Guyana" },
  { callingCode: "+593", flag: "🇪🇨", countryCode: "EC", name: "Ecuador" },
  { callingCode: "+594", flag: "🇬🇫", countryCode: "GF", name: "French Guiana" },
  { callingCode: "+595", flag: "🇵🇾", countryCode: "PY", name: "Paraguay" },
  { callingCode: "+596", flag: "🇲🇶", countryCode: "MQ", name: "Martinique" },
  { callingCode: "+597", flag: "🇸🇷", countryCode: "SR", name: "Suriname" },
  { callingCode: "+598", flag: "🇺🇾", countryCode: "UY", name: "Uruguay" },
  { callingCode: "+599", flag: "	AN", countryCode: "Netherlands", name: "Antilles" },
  { callingCode: "+60", flag: "🇲🇾", countryCode: "MY", name: "Malaysia" },
  { callingCode: "+61", flag: "🇦🇺", countryCode: "AU", name: "Australia" },
  { callingCode: "+61", flag: "🇨🇽", countryCode: "CX", name: "Christmas Island" },
  { callingCode: "+61", flag: "🇨🇨", countryCode: "CC", name: "Cocos (Keeling) Islands" },
  { callingCode: "+62", flag: "🇮🇩", countryCode: "ID", name: "Indonesia" },
  { callingCode: "+63", flag: "🇵🇭", countryCode: "PH", name: "Philippines" },
  { callingCode: "+64", flag: "🇳🇿", countryCode: "NZ", name: "New Zealand" },
  { callingCode: "+64", flag: "🇵🇳", countryCode: "PN", name: "Pitcairn" },
  { callingCode: "+65", flag: "🇸🇬", countryCode: "SG", name: "Singapore" },
  { callingCode: "+66", flag: "🇹🇭", countryCode: "TH", name: "Thailand" },
  { callingCode: "+670", flag: "🇹🇱", countryCode: "TL", name: "Timor-Leste" },
  { callingCode: "+672", flag: "🇦🇶", countryCode: "AQ", name: "Antarctica" },
  { callingCode: "+672", flag: "🇭🇲", countryCode: "HM", name: "Heard Island and Mcdonald Islands" },
  { callingCode: "+672", flag: "🇳🇫", countryCode: "NF", name: "Norfolk Island" },
  { callingCode: "+673", flag: "🇧🇳", countryCode: "BN", name: "Brunei Darussalam" },
  { callingCode: "+674", flag: "🇳🇷", countryCode: "NR", name: "Nauru" },
  { callingCode: "+675", flag: "🇵🇬", countryCode: "PG", name: "Papua New Guinea" },
  { callingCode: "+676", flag: "🇹🇴", countryCode: "TO", name: "Tonga" },
  { callingCode: "+677", flag: "🇸🇧", countryCode: "SB", name: "Solomon Islands" },
  { callingCode: "+678", flag: "🇻🇺", countryCode: "VU", name: "Vanuatu" },
  { callingCode: "+679", flag: "🇫🇯", countryCode: "FJ", name: "Fiji" },
  { callingCode: "+680", flag: "🇵🇼", countryCode: "PW", name: "Palau" },
  { callingCode: "+681", flag: "🇼🇫", countryCode: "WF", name: "Wallis and Futuna" },
  { callingCode: "+682", flag: "🇨🇰", countryCode: "CK", name: "Cook Islands" },
  { callingCode: "+683", flag: "🇳🇺", countryCode: "NU", name: "Niue" },
  { callingCode: "+685", flag: "🇼🇸", countryCode: "WS", name: "Samoa" },
  { callingCode: "+686", flag: "🇰🇮", countryCode: "KI", name: "Kiribati" },
  { callingCode: "+687", flag: "🇳🇨", countryCode: "NC", name: "New Caledonia" },
  { callingCode: "+688", flag: "🇹🇻", countryCode: "TV", name: "Tuvalu" },
  { callingCode: "+689", flag: "🇵🇫", countryCode: "PF", name: "French Polynesia" },
  { callingCode: "+690", flag: "🇹🇰", countryCode: "TK", name: "Tokelau" },
  { callingCode: "+691", flag: "🇫🇲", countryCode: "FM", name: "Micronesia, Federated States of Micronesia" },
  { callingCode: "+692", flag: "🇲🇭", countryCode: "MH", name: "Marshall Islands" },
  { callingCode: "+7", flag: "🇰🇿", countryCode: "KZ", name: "Kazakhstan" },
  { callingCode: "+7", flag: "🇷🇺", countryCode: "RU", name: "Russia" },
  { callingCode: "+81", flag: "🇯🇵", countryCode: "JP", name: "Japan" },
  { callingCode: "+82", flag: "🇰🇷", countryCode: "KR", name: "Korea, Republic of South Korea" },
  { callingCode: "+84", flag: "🇻🇳", countryCode: "VN", name: "Vietnam" },
  { callingCode: "+850", flag: "🇰🇵", countryCode: "KP", name: "Korea, Democratic People's Republic of Korea" },
  { callingCode: "+852", flag: "🇭🇰", countryCode: "HK", name: "Hong Kong" },
  { callingCode: "+853", flag: "🇲🇴", countryCode: "MO", name: "Macao" },
  { callingCode: "+855", flag: "🇰🇭", countryCode: "KH", name: "Cambodia" },
  { callingCode: "+856", flag: "🇱🇦", countryCode: "LA", name: "Laos" },
  { callingCode: "+86", flag: "🇨🇳", countryCode: "CN", name: "China" },
  { callingCode: "+880", flag: "🇧🇩", countryCode: "BD", name: "Bangladesh" },
  { callingCode: "+886", flag: "🇹🇼", countryCode: "TW", name: "Taiwan" },
  { callingCode: "+90", flag: "🇹🇷", countryCode: "TR", name: "Türkiye" },
  { callingCode: "+91", flag: "🇮🇳", countryCode: "IN", name: "India" },
  { callingCode: "+92", flag: "🇵🇰", countryCode: "PK", name: "Pakistan" },
  { callingCode: "+93", flag: "🇦🇫", countryCode: "AF", name: "Afghanistan" },
  { callingCode: "+94", flag: "🇱🇰", countryCode: "LK", name: "Sri Lanka" },
  { callingCode: "+95", flag: "🇲🇲", countryCode: "MM", name: "Myanmar" },
  { callingCode: "+960", flag: "🇲🇻", countryCode: "MV", name: "Maldives" },
  { callingCode: "+961", flag: "🇱🇧", countryCode: "LB", name: "Lebanon" },
  { callingCode: "+962", flag: "🇯🇴", countryCode: "JO", name: "Jordan" },
  { callingCode: "+963", flag: "🇸🇾", countryCode: "SY", name: "Syrian Arab Republic" },
  { callingCode: "+964", flag: "🇮🇶", countryCode: "IQ", name: "Iraq" },
  { callingCode: "+965", flag: "🇰🇼", countryCode: "KW", name: "Kuwait" },
  { callingCode: "+966", flag: "🇸🇦", countryCode: "SA", name: "Saudi Arabia" },
  { callingCode: "+967", flag: "🇾🇪", countryCode: "YE", name: "Yemen" },
  { callingCode: "+968", flag: "🇴🇲", countryCode: "OM", name: "Oman" },
  { callingCode: "+970", flag: "🇵🇸", countryCode: "PS", name: "Palestinian Territory, Occupied" },
  { callingCode: "+971", flag: "🇦🇪", countryCode: "AE", name: "United Arab Emirates" },
  { callingCode: "+972", flag: "🇮🇱", countryCode: "IL", name: "Israel" },
  { callingCode: "+973", flag: "🇧🇭", countryCode: "BH", name: "Bahrain" },
  { callingCode: "+974", flag: "🇶🇦", countryCode: "QA", name: "Qatar" },
  { callingCode: "+975", flag: "🇧🇹", countryCode: "BT", name: "Bhutan" },
  { callingCode: "+976", flag: "🇲🇳", countryCode: "MN", name: "Mongolia" },
  { callingCode: "+977", flag: "🇳🇵", countryCode: "NP", name: "Nepal" },
  { callingCode: "+98", flag: "🇮🇷", countryCode: "IR", name: "Iran, Islamic Republic of Persian Gulf" },
  { callingCode: "+992", flag: "🇹🇯", countryCode: "TJ", name: "Tajikistan" },
  { callingCode: "+993", flag: "🇹🇲", countryCode: "TM", name: "Turkmenistan" },
  { callingCode: "+994", flag: "🇦🇿", countryCode: "AZ", name: "Azerbaijan" },
  { callingCode: "+995", flag: "🇬🇪", countryCode: "GE", name: "Georgia" },
  { callingCode: "+996", flag: "🇰🇬", countryCode: "KG", name: "Kyrgyzstan" },
  { callingCode: "+998", flag: "🇺🇿", countryCode: "UZ", name: "Uzbekistan" },
]
