export const BANKES_DATA = [
  {
    faName: "بانک ملت",
    enName: "mellat bank",
    icon: require("@assets/image/banks/melat.png"),
    cardPan: "610433",
  },
  {
    faName: "بانک ملت",
    enName: "mellat bank",
    icon: require("@assets/image/banks/melat.png"),
    cardPan: "991975",
  },
  {
    faName: "بانک اقتصاد نوین",
    enName: "eghtesad novin Bank",
    icon: require("@assets/image/banks/eqtesadNovin.png"),
    cardPan: "627412",
  },
  {
    faName: "بانک پاسارگاد",
    enName: "pasargad Bank",
    icon: require("@assets/image/banks/pasargad.png"),
    cardPan: "502229",
  },
  {
    faName: "بانک پاسارگاد",
    enName: "pasargad Bank",
    icon: require("@assets/image/banks/pasargad.png"),
    cardPan: "639347",
  },
  {
    faName: "بانک ایران زمین",
    enName: "iran zamin Bank",
    icon: require("@assets/image/banks/iranZamin.png"),
    cardPan: "505785",
  },
  {
    faName: "بانک شهر",
    enName: "iran zamin Bank",
    icon: require("@assets/image/banks/shahr.png"),
    cardPan: "502806",
  },
  {
    faName: "بانک پارسیان",
    enName: "parsian Bank",
    icon: require("@assets/image/banks/parsian.png"),
    cardPan: "622106",
  },
  {
    faName: "بانک پارسیان",
    enName: "parsian Bank",
    icon: require("@assets/image/banks/parsian.png"),
    cardPan: "639194",
  },
  {
    faName: "بانک پارسیان",
    enName: "parsian Bank",
    icon: require("@assets/image/banks/parsian.png"),
    cardPan: "627884",
  },
  {
    faName: "بانک توسعه تعاون",
    enName: "tosee taavon Bank",
    icon: require("@assets/image/banks/toseeTaavon.png"),
    cardPan: "502908",
  },
  {
    faName: "بانک کارآفرین",
    enName: "kar afarin Bank",
    icon: require("@assets/image/banks/karAfarin.png"),
    cardPan: "502910",
  },
  {
    faName: "بانک کارآفرین",
    enName: "kar afarin Bank",
    icon: require("@assets/image/banks/karAfarin.png"),
    cardPan: "627488",
  },
  {
    faName: "بانک دی",
    enName: "dey Bank",
    icon: require("@assets/image/banks/dey.png"),
    cardPan: "502938",
  },
  {
    faName: "بانک گردشگری",
    enName: "gardeshgari Bank",
    icon: require("@assets/image/banks/gardeshgari.png"),
    cardPan: "505416",
  },
  {
    faName: "بانک تجارت",
    enName: "tejarat Bank",
    icon: require("@assets/image/banks/tejarat.png"),
    cardPan: "627353",
  },
  {
    faName: " بانک سپه",
    enName: "sepah Bank",
    icon: require("@assets/image/banks/sepah.png"),
    cardPan: "589210",
  },
  {
    faName: "بانک رفاه کارگران",
    enName: "sepah Bank",
    icon: require("@assets/image/banks/refahKargaran.png"),
    cardPan: "589463",
  },
  {
    faName: "بانک صادرات ایران",
    enName: "iran saderat Bank",
    icon: require("@assets/image/banks/saderat.png"),
    cardPan: "603769",
  },
  {
    faName: "بانک کشاورزی",
    enName: "keshavarzi Bank",
    icon: require("@assets/image/banks/keshavarzi.png"),
    cardPan: "603770",
  },
  {
    faName: "بانک کشاورزی",
    enName: "keshavarzi Bank",
    icon: require("@assets/image/banks/keshavarzi.png"),
    cardPan: "639217",
  },
  {
    faName: "بانک ملی ایران",
    enName: "iran meli Bank",
    icon: require("@assets/image/banks/meli.png"),
    cardPan: "603799",
  },
  {
    faName: "بانک قرض الحسنه مهر ایران",
    enName: "iran mehr Bank",
    icon: require("@assets/image/banks/mehrIran.png"),
    cardPan: "606373",
  },
  {
    faName: "بانک سامان",
    enName: "saman Bank",
    icon: require("@assets/image/banks/saman.png"),
    cardPan: "621986",
  },
  {
    faName: "بانک سرمایه",
    enName: "sarmaye Bank",
    icon: require("@assets/image/banks/sarmaye.png"),
    cardPan: "639607",
  },
  {
    faName: "بانک سینا",
    enName: "sina Bank",
    icon: require("@assets/image/banks/sina.png"),
    cardPan: "639346",
  },
  {
    faName: "بانک توسعه صادرات ایران",
    enName: "iran tosee saderat Bank",
    icon: require("@assets/image/banks/toseeSaderat.png"),
    cardPan: "627648",
  },
  {
    faName: "پست بانک ایران",
    enName: "iran post Bank",
    icon: require("@assets/image/banks/postBank.png"),
    cardPan: "627760",
  },
  {
    faName: "بانک مسکن",
    enName: "maskan Bank",
    icon: require("@assets/image/banks/maskan.png"),
    cardPan: "628023",
  },
  {
    faName: "بانک آینده",
    enName: "ayande Bank",
    icon: require("@assets/image/banks/ayande.png"),
    cardPan: "636214",
  },
  {
    faName: "بانک رسالت",
    enName: "resalat Bank",
    icon: require("@assets/image/banks/resalat.png"),
    cardPan: "504172",
  },
];
