query bannerList($page: PageType, $search: String) {
  bannerList(search: $search, page: $page) {
    pageCount
    count
    data {
      id
      url
      title
      avatarS3 {
        large
        medium
        small
      }
    }
  }
}
