query bannerList($page: PageType, $search: String) {
  bannerList(search: $search) {
    pageCount
    count
    data {
      id
      url
      title
      avatarS3 {
        large
        medium
        small
      }
    }
    pageCount
  }
}
