query BannerList($page: PageType, $search: String) {
  bannerList(page: $page, search: $search) {
    count
    data {
      avatarS3 {
        large
        medium
        small
      }
      id
      title
      url
    }
    pageCount
  }
}
