query categoryList($page: PageType, $search: String) {
  categoryList(page: $page, search: $search) {
    pageCount
    count
    data {
      id
      name
      displayName
      avatarS3 {
        large
        medium
        small
      }
    }
    pageCount
  }
}
