query hostComment($pk: ID!) {
  projectDetail(pk: $pk) {
    name
    commentSet {
      text
      createdDate
      dislikeCount
      likeCount
      id
      user {
        fullname
        displayName
      }
      nestedComment {
        text
        createdDate
        dislikeCount
        likeCount
        id
        user {
          fullname
        }
      }
    }
  }
}
