query myNGODetailProjectTransactionSet {
  NGODetail {
    id
    projectTransactionSet {
      dateEnd
      dateStart
      id
      owner {
        phoneNumber
        fullname
        id
        avatarS3 {
          large
          medium
          small
          orginal
        }
      }
      guest {
        guestNumber
        gender
        childAccept
      }
      project {
        name
        id
      }
      status {
        isActive
        step {
          displayName
          name
        }
      }
    }
  }
}
