query myNGODetail {
  NGODetail {
    id
    projectSet {
      id
      creator {
        id
      }
      accommodation {
        id
        address
        province
        city
        avatarS3 {
          large
          medium
          small
        }
      }
      name
      description
      modifiedDate
      dateStart
      dateEnd
      gender
      requestFrom
      price
      discount
      tax
      statusStep
      statusActivation
      facilities {
        id
      }
      tags {
        id
      }
      categories {
        id
      }
      createdDate
      capacity {
        id
      }
      transactionSet {
        id
      }
      capacityReserved {
        male
        female
        child
        allCap
      }
      freeCapacity {
        male
        female
        child
        allCap
      }
      __typename
    }
    tourSet {
      id
      title
      description
      startTime
      endTime
      statusStep
      statusActivation
      createdDate
      origin {
        ... on AccommodationQueryType {
          id
          province
          city
          address
          lat
          lng
          avatarS3 {
            large
            medium
            small
          }
        }
        ... on ProjectQueryType {
          id
        }
      }
      destination {
        ... on AccommodationQueryType {
          id
          province
          city
          address
          lat
          lng
          avatarS3 {
            large
            medium
            small
          }
        }
        ... on ProjectQueryType {
          id
        }
        __typename
      }
      avatarS3 {
        large
        medium
        small
      }
      packages {
        id
        title
        price
      }
      capacity {
        id
        male
        female
        child
      }
      facilities {
        id
        faName
        enName
        arName
      }
    }
    tourTransactionSet {
      id
      status {
        isActive
        step
      }
      owner {
        avatarS3 {
          large
          medium
          small
        }
        id
        fullname
        phoneNumber
      }
      tourPackage {
        tour {
          id
          title
        }
      }
      tourGuests {
        avatarS3 {
          large
          medium
          small
        }
        id
        firstname
        lastname
        phoneNumber
      }
    }
    projectTransactionSet {
      dateEnd
      dateStart
      id
      owner {
        phoneNumber
        fullname
        id
        avatarS3 {
          large
          medium
          small
        }
      }
      guestSet {
        id
      }
      project {
        name
        id
      }
      status {
        isActive
        step
      }
    }
  }
}
