query myNGODetailTourSet {
  NGODetail {
    id
    isVerify
    verifyDescription
    tourSet {
      id
      title
      description
      startTime
      endTime
      statusStep {
        displayName
        name
      }
      statusActivation
      createdDate
      modifiedDate
      origin {
        ... on AccommodationQueryType {
          id
          province
          city
          address
          lat
          lng
          avatarS3 {
            large
            medium
            small
            orginal
          }
        }
        ... on ProjectQueryType {
          id
        }
      }
      destination {
        ... on AccommodationQueryType {
          id
          province
          city
          address
          lat
          lng
          avatarS3 {
            large
            medium
            small
            orginal
          }
        }
        ... on ProjectQueryType {
          id
        }
        __typename
      }
      avatarS3 {
        large
        medium
        small
        orginal
      }
      packages {
        id
        title
        price
        discount
      }
      capacity {
        gender
        childAccept
        guestNumber
      }
      facilities {
        id
        faName
        enName
        arName
      }
    }
  }
}
