query myNGODetailTourTransactionSet {
  NGODetail {
    id
    tourTransactionSet {
      id
      status {
        isActive
        step{
        displayName
        name
      }
      }
      owner {
        avatarS3 {
          large
          medium
          small
        }
        id
        fullname
        phoneNumber
      }
      tourPackage {
        tour {
          id
          title
        }
      }
      tourGuests {
        avatarS3{
          large
          medium
          small
        }
        id
        firstname
        lastname
        phoneNumber
      }
    }
  }
}
