query myNGODetail {
  NGODetail {
    id
    kind
    title
    address
    isVerify
    verifyDescription
    description
    contactNumber
    user {
      id
      email
      phoneNumber
    }
    projectSet {
      id
      creator {
        id
      }
      accommodation {
        id
        address
        province
        city
        avatarS3 {
          large
          medium
          small
        }
      }
      name
      description
      modifiedDate
      dateStart
      dateEnd
      gender
      requestFrom
      price
      discount
      tax
      statusStep
      statusActivation
      facilities {
        id
      }
      tags {
        id
      }
      categories {
        id
      }
      createdDate
      transactionSet {
        id
      }
      capacityReserved {
        male
        female
        allCap
      }
      freeCapacity {
        male
        female
        allCap
      }
      __typename
    }
    bannerS3 {
      large
      medium
      small
    }
    contactNumber
    description
    isVerify
    kind
    lat
    lng
  }
}
