query myNGODetail {
  NGODetail {
    id
    title
    address
    avatarS3 {
      large
      medium
      small
    }
    bannerS3 {
      large
      medium
      small
    }
    contactNumber
    description
    isVerify
    kind
    lat
    lng
  }
}
