query myUserDetailProjectSet {
  userDetail {
    id
    isNgo
    ngo {
      isVerify
      verifyDescription
    }
    projectSet {
      id
      creator {
        id
      }
      accommodation {
        id
        address
        province
        city
        lat
        lng
        avatarS3 {
          large
          medium
          small
        }
      }
      name
      description
      modifiedDate
      dateStart
      dateEnd
      gender
      requestFrom
      price
      discount
      tax
      statusStep
      statusActivation
      facilities {
        id
        faName
        enName
      }
      tags {
        id
      }
      categories {
        id
      }
      createdDate

      transactionSet {
        id
      }
      capacityReserved {
        male
        female
        allCap
      }
      freeCapacity {
        male
        female
        allCap
      }
    }
  }
}
