query myUserDetailProjectSet {
  userDetail {
    id
    projectSet {
      id
      creator {
        id
      }
      accommodation {
        id
        address
        province
        city
        avatarS3 {
          large
          medium
          small
        }
      }
      name
      description
      modifiedDate
      dateStart
      dateEnd
      gender
      requestFrom
      price
      discount
      tax
      statusStep
      statusActivation
      facilities {
        id
      }
      tags {
        id
      }
      categories {
        id
      }
      createdDate
      capacity {
        id
      }
      transactionSet {
        id
      }
      capacityReserved {
        male
        female
        allCap
      }
      freeCapacity {
        male
        female
        allCap
      }
      __typename
    }
  }
}
