query NGODetail($pk: ID) {
  NGODetail(pk: $pk) {
    id
    title
    address
    description
    avatarS3 {
      large
      medium
      small
    }
    user {
      id
      avatarS3 {
        large
        medium
        small
      }
    }
    tourSet {
      id
      title
    }
    projectSet {
      id
      # type
      name
      price
      dateStart
      dateEnd
      gender
      requestFrom
      tax
      description
      statusStep
      createdDate
      capacity {
        id
        male
        female
        child
      }
      categories {
        id
        name
        displayName
        avatarS3 {
          large
          medium
          small
        }
      }
      tags {
        id
        name
        displayName
      }
      facilities {
        id
        faName
        enName
        arName
      }
      accommodation {
        id
        avatarS3 {
          large
          medium
          small
        }
      }
    }
    tourTransactionSet {
      id
      status {
        isActive
        step
      }
      owner {
        avatarS3 {
          large
          medium
          small
        }
        id
        fullname
        phoneNumber
      }
      tourPackage {
        tour {
          title
        }
      }
      tourGuests {
        avatarS3 {
          large
          medium
          small
        }
        id
        firstname
        lastname
        phoneNumber
      }
    }
  }
}
