query projectList($search: String, $sort: SortType, $filter: ProjectFilterType, $page: PageType!) {
  projectList(search: $search, sort: $sort, filter: $filter, page: $page) {
    pageCount
    count
    data {
      id
      name
      price
      dateStart
      dateEnd
      discount
      rate{
        avgRate
      }
      capacity {
        childAccept
        gender
        guestNumber
      }
      tags {
        id
        name
      }
      accommodation {
        id
        address
        avatarS3 {
          small
        }
      }
    }
  }
}
