query projectprojectTransactionList($filter: ProjectTransactionFilterType) {
  projectprojectTransactionList(filter: $filter) {
    id
    dateEnd
    dateStart
    description
    invoiceNumber
    createdDate
    owner {
      id
      lastName
      firstName
    }
    status {
      step
      isActive
    }
    guestSet {
      name
    }
    project {
      id
      name
      tax
      price
      description
      facilities {
        id
        enName
      }
      accommodation {
        id
        address
        lat
        lng
        avatarS3 {
          small
        }
      }
    }
  }
}
