query projectList(
  $search: String
  $filter: ProjectFilterType
  $page: PageType!
) {
  projectList(search: $search, filter: $filter, page: $page) {
    pageCount
    count
    data {
      id
      name
      price
      dateStart
      dateEnd
      capacity {
        id
        male
        female
        child
      }
      tags {
        id
        name
      }
      accommodation {
        id
        address
        avatarS3 {
          small
        }
      }
    }
  }
}
