query projectTransactionDetail($pk: ID!) {
  projectTransactionDetail(pk: $pk) {
    id
    dateEnd
    dateStart
    description
    modifiedDate
    invoiceNumber
    purchaseRefId
    createdDate
    owner {
      id
      fullname
      firstname
    }
    status {
      step
      isActive
    }
    guest {
      guestNumber
      gender
      childAccept
    }
    project {
      id
      name
      tax
      price
      creator {
        id
        firstname
        fullname
        phoneNumber
      }
      description
      categories {
        name
      }
      facilities {
        id
        enName
      }
      accommodation {
        id
        address
        lat
        lng
        avatarS3 {
          small
          medium
          large
        }
      }
    }
  }
}
