query projectDetail($pk: ID!) {
  projectDetail(pk: $pk) {
    ... on ProjectQueryType {
      id
      name
      price
      gender
      dateEnd
      discount
      dateStart
      statusStep
      description
      tags {
        id
        name
      }
      capacity {
        childAccept
        gender
        guestNumber
      }
      facilities {
        id
        enName
        faName
        arName
      }
      categories {
        name
        id
      }
      creator {
        id
        fullname
        firstname
        phoneNumber
        ngo {
          id
        }

        avatarS3 {
          small
          medium
          large
        }
        projectSet {
          id
          name
          price
          accommodation {
            id
            address
            avatarS3 {
              large
              medium
              small
            }
          }
        }
      }
      accommodation {
        id
        lat
        lng
        address
        avatarS3 {
          large
          medium
          small
        }
      }
    }
  }
}
