query projectTransactionDetail($pk: ID!) {
  projectTransactionDetail(pk: $pk) {
    id
    dateEnd
    dateStart
    owner {
      id
      lastname
      firstname
    }
    guestSet {
      name
    }
    project {
      id
      tax
      name
      price
      accommodation {
        id
        address
      }
    }
  }
}
