query projectListSearch(
  $search: String
  $sort: SortType = { descending: true }
  $filter: ProjectFilterType
  $page: PageType!
) {
  projectList(search: $search, sort: $sort, filter: $filter, page: $page) {
    pageCount
    count
    data {
      id
      name
      price
      discount
      modifiedDate
      accommodation {
        id
        lat
        lng
        address
        avatarS3 {
          small
        }
      }
    }
  }
}
