query ProjectTransactionList($page: PageType, $filter: ProjectTransactionFilterType) {
  projectTransactionList(page: $page, filter: $filter) {
    count
    pageCount
    data {
      id
      dateEnd
      dateStart
      description
      modifiedDate
      invoiceNumber
      createdDate
      owner {
        id
        fullname
        firstname
      }
      status {
        step {
          displayName
          name
        }
        isActive
      }
      guest {
        guestNumber
        gender
        childAccept
      }
      project {
        id
        name
        tax
        price
        discount
        description
        categories {
          name
        }
        facilities {
          id
          enName
        }
        accommodation {
          id
          address
          lat
          lng
          avatarS3 {
            small
            medium
            large
          }
        }
      }
    }
  }
}
