query tourDetail($pk: ID!) {
  tourDetail(pk: $pk) {
    ... on TourQueryType {
      id
      title
      endTime
      startTime
      statusStep
      description
      NGO {
        id
        isVerify
        verifyDescription
        user {
          id
          fullname
          phoneNumber
          avatarS3 {
            small
          }
          ngo {
            id
          }
        }
        tourSet {
          id
          title
          packages {
            id
            title
            price
          }
          destination {
            ... on AccommodationQueryType {
              address
              avatarS3 {
                large
                medium
                small
              }
            }
          }
        }
      }
      facilities {
        id
        enName
        faName
        arName
      }
      destination {
        ... on AccommodationQueryType {
          id
          address
          lat
          lng
        }
      }
      packages {
        id
        title
        price
      }
      avatarS3 {
        medium
        large
        small
      }
    }
  }
}
