query tourList($search: String, $sort: SortType, $filter: TourFilterType, $page: PageType!) {
  tourList(search: $search, sort: $sort, filter: $filter, page: $page) {
    count
    data {
      id
      title
      description
      startTime
      endTime
      statusActivation
      rate {
        avgRate
      }
      NGO {
        id
        title
        user {
          id
          fullname
          phoneNumber
          avatarS3 {
            small
            medium
            large
            orginal
          }
        }

        tourSet {
          id
          title
          packages {
            id
            title
            price
            discount
          }
          destination {
            ... on AccommodationQueryType {
              address
              avatarS3 {
                large
                medium
                small
                orginal
              }
            }
          }
        }
      }
      # capacity {
      #   id
      #   male
      #   female
      #   child
      # }
      facilities {
        id
        enName
        faName
        arName
      }
      destination {
        ... on AccommodationQueryType {
          id
          address
          lat
          lng
        }
      }
      packages {
        id
        title
        price
        discount
      }
      avatarS3 {
        medium
        large
        small
        orginal
      }
    }
  }
}
