query tourTransactionDetail($pk: ID!) {
  tourTransactionDetail(pk: $pk) {
    id
    createdDate
    description
    modifiedDate
    invoiceNumber
    purchaseRefId
    tourGuests {
      id
    }
    tourguestSet {
      id
      birthday
      lastname
      firstname
      phoneNumber

      identifyNumber
      gender
    }
    status {
      isActive
      step{
        displayName
        name
      }
    }
    tourPackage {
      title
      price
      discount
      id
      tour {
        avatarS3 {
          small
          medium
        }
        id
        title
        endTime
        startTime
        destination {
          ... on AccommodationQueryType {
            id
            lat
            lng
            address
            avatarS3 {
              small
              medium
              large
            }
          }
        }
      }
    }
  }
}
