query tourComment($pk: ID!) {
  tourDetail(pk: $pk) {
    title
    commentSet {
      text
      createdDate
      dislikeCount
      likeCount
      id
      user {
        fullname
      }
      nestedComment {
      text
      createdDate
      dislikeCount
      likeCount
      id
      user {
        fullname
      }
      }
    }
  }
}
