query userTransactionDetail($pk: ID!) {
  userTransactionDetail(pk: $pk) {
    id
    dateEnd
    dateStart
    owner {
      id
      lastName
      firstName
    }
    guestSet {
      name
    }
    project {
      id
      tax
      name
      price
      accommodation {
        id
        address
      }
    }
  }
}
