query userDetailProfile {
  userDetail {
    id
    bio
    isNgo
    username
    firstname
    lastname
    fullname
    avatarS3 {
      small
      medium
      large
      orginal
    }
    ngo {
      id
      title
      isVerify
      verifyDescription
      avatarS3 {
        small
        medium
        large
        orginal
      }
    }
  }
}
