query userDetailProfile {
  userDetail {
    id
    isNgo
    username
    avatarS3 {
      small
    }
    ngo {
      id
      title
      isVerify
      verifyDescription
      avatarS3 {
        small
      }
    }
  }
}
