query walletTransactionList {
  walletTransactionList {
    data {
      action
      source {
        ... on BackCardQueryType {
          id
          title
          cardPan
        }
        ... on WalletQuryType {
          id
        }
      }
      reference {
        ... on BackCardQueryType {
          id
          cardPan
          iban
        }
        ... on WalletQuryType {
          id
          balance
        }
      }
      purchaseRefId
      modifiedTime
      invoiceNumber
      id
      description
      amount
      statusStep
    }
  }
}
