// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/home/s/Desktop/mofid-trip/node_modules/react');
var { Component } = React;
var ReactNative = require('/home/s/Desktop/mofid-trip/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('mofid-trip', appParameters);
});
require('/home/s/Desktop/mofid-trip/index.android.js');